version: "3"
services:
  fastapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: fastapi
    hostname: fastapi
    ports:
      - 8081:8000
    restart: always
    stop_grace_period: 120s
