name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:fastapi appropriate/curl -s --retry 2 --retry-connrefused http://http://127.0.0.1:8081/
