# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  slack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Post Slack messages

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@v1.0.7
        with:
          args: '{\"channel\":\"C03EB3C343T\",\"text\":\"Hello world\"}'
